# List of ruls:
# https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases

[global]
line-length = 100
disable = [
  "MD013", # Maximum line length
  "MD034", # Put `<angle brackets>` around URLs
  "MD025", # Only one h1 heading allowed
  "MD040", # Code blocks should have a language
  "MD031", # Code blocks should be surrounded by blank lines
]

[MD060] # Table formatting
enabled = true
